In [15]:
import numpy as np
import torch
cf=np.load('/data1/jiajing/worksapce/Project/Zero_Shot/Exp/training_lr_3*1e-4/cm.npy')



In [16]:
print(cf)

[[145.   0.   0.   0.   7.   2.   7.   0.]
 [  0. 115.   0.   0.   1.   0.   0.  13.]
 [  0.   0. 168.   0.   1.   1.   0.   0.]
 [ 27.   0.   0.  93.   0.   0.   4.  33.]
 [  9.   0.   0.   0. 122.   4.   1.   0.]
 [  9.   0.   0.   0.   2. 109.  13.   0.]
 [ 18.   1.   1.   0.   0.   0. 142.   3.]
 [  0.   7.   0.  45.  18.   0.   0. 124.]]


In [14]:
acc=np.trace(cf)/np.sum(cf)
print("accuracy is ",acc)

num_cls=cf.shape[0]
for i in range(num_cls):
    iou=cf[i,i]/(np.sum(cf[i,:])+np.sum(cf[:,i])-cf[i,i])
    print(iou)

accuracy is  0.8176706827309237
0.6473214285714286
0.8394160583941606
0.9824561403508771
0.4603960396039604
0.7393939393939394
0.7785714285714286
0.7473684210526316
0.5102880658436214
